-- MySQL Script generated by MySQL Workbench
-- Sat Apr 16 02:22:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema renueva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema renueva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `renueva` DEFAULT CHARACTER SET utf8mb4 ;
USE `renueva` ;

-- -----------------------------------------------------
-- Table `renueva`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cat` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`articulod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`articulod` (
  `Ar_id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_categoria` INT(11) NULL DEFAULT NULL,
  `Ar_descripcion` VARCHAR(200) NOT NULL,
  `Ar_precioVenta` DECIMAL(11,2) NOT NULL,
  `Ar_nombre` VARCHAR(50) NOT NULL,
  `Ar_stock` INT(11) NOT NULL,
  `Ar_precioCosto` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`Ar_id`),
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `articulod_ibfk_1`,
    FOREIGN KEY (`id_categoria`)
    REFERENCES `renueva`.`categoria` (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`inventario` (
  `inv_id` INT(11) NOT NULL AUTO_INCREMENT,
  `inv_date` VARCHAR(14) NOT NULL,
  `inv_total` INT(11) NOT NULL,
  `Ar_id` INT(11) NOT NULL,
  PRIMARY KEY (`inv_id`),
  INDEX `Ar_id` (`Ar_id` ASC) VISIBLE,
  CONSTRAINT `inventario_ibfk_1`
    FOREIGN KEY (`Ar_id`)
    REFERENCES `renueva`.`articulod` (`Ar_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`pedido` (
  `idventa` ,
  `fecha_hora` VARCHAR(50) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `total` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idventa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`pedido_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`pedido_articulo` (
  `pd_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Ar_id` INT(11) NOT NULL,
  `iduser` INT NOT NULL,
  `pedido_idventa` INT(11) NOT NULL,
  PRIMARY KEY (`pd_id`),
  INDEX `Ar_id` (`Ar_id` ASC) VISIBLE,
  INDEX `fk_pedido_articulo_pedido1_idx` (`pedido_idventa` ASC) VISIBLE,
  CONSTRAINT `pedido_articulo_ibfk_1`
    FOREIGN KEY (`Ar_id`)
    REFERENCES `renueva`.`articulod` (`Ar_id`),
  CONSTRAINT `fk_pedido_articulo_pedido1`
    FOREIGN KEY (`pedido_idventa`)
    REFERENCES `renueva`.`pedido` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`usuario` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `administrator_b` BIT(1) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(80) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`iduser`),
  CONSTRAINT `fk_usuario_pedido_articulo1`
    FOREIGN KEY (`iduser`)
    REFERENCES `renueva`.`pedido_articulo` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
