-- MySQL Script generated by MySQL Workbench
-- Mon Apr 25 21:05:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema renueva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema renueva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `renueva` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `id_rol` INT NOT NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `renueva`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`usuario` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `id_rol` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(80) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(50) NOT NULL,
  `rol_id_rol` INT NOT NULL,
  PRIMARY KEY (`iduser`, `rol_id_rol`),
  INDEX `fk_usuario_rol1_idx` (`rol_id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `mydb`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`citas` (
  `idcitas` INT NOT NULL,
  `iduser` INT NULL,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `id_servicio` INT NULL,
  `comentario` VARCHAR(100) NULL,
  `citascol` VARCHAR(45) NULL,
  `usuario_iduser` INT(11) NOT NULL,
  PRIMARY KEY (`idcitas`, `usuario_iduser`),
  INDEX `fk_citas_usuario1_idx` (`usuario_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_citas_usuario1`
    FOREIGN KEY (`usuario_iduser`)
    REFERENCES `renueva`.`usuario` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios` (
  `idservicios` INT NOT NULL,
  `servicios` VARCHAR(45) NULL,
  PRIMARY KEY (`idservicios`))
ENGINE = InnoDB;

USE `renueva` ;

-- -----------------------------------------------------
-- Table `renueva`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cat` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`articulod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`articulod` (
  `Ar_id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_categoria` INT(11) NULL DEFAULT NULL,
  `Ar_descripcion` VARCHAR(200) NOT NULL,
  `Ar_precioVenta` DECIMAL(11,2) NOT NULL,
  `Ar_nombre` VARCHAR(50) NOT NULL,
  `Ar_stock` INT(11) NOT NULL,
  `Ar_precioCosto` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`Ar_id`),
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `articulod_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `renueva`.`categoria` (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`inventario` (
  `inv_id` INT(11) NOT NULL AUTO_INCREMENT,
  `inv_date` VARCHAR(14) NOT NULL,
  `inv_total` INT(11) NOT NULL,
  `Ar_id` INT(11) NOT NULL,
  PRIMARY KEY (`inv_id`),
  INDEX `Ar_id` (`Ar_id` ASC) VISIBLE,
  CONSTRAINT `inventario_ibfk_1`
    FOREIGN KEY (`Ar_id`)
    REFERENCES `renueva`.`articulod` (`Ar_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`pedido` (
  `idventa` INT(11) NOT NULL,
  `fecha_hora` VARCHAR(50) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `total` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idventa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`pedido_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`pedido_articulo` (
  `pd_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Ar_id` INT(11) NOT NULL,
  `iduser` INT(11) NOT NULL,
  `idventa` INT(11) NOT NULL,
  PRIMARY KEY (`pd_id`),
  INDEX `Ar_id` (`Ar_id` ASC) VISIBLE,
  INDEX `idventa` (`idventa` ASC) VISIBLE,
  INDEX `iduser` (`iduser` ASC) VISIBLE,
  CONSTRAINT `pedido_articulo_ibfk_1`
    FOREIGN KEY (`Ar_id`)
    REFERENCES `renueva`.`articulod` (`Ar_id`),
  CONSTRAINT `pedido_articulo_ibfk_2`
    FOREIGN KEY (`idventa`)
    REFERENCES `renueva`.`pedido` (`idventa`),
  CONSTRAINT `pedido_articulo_ibfk_3`
    FOREIGN KEY (`iduser`)
    REFERENCES `renueva`.`usuario` (`iduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
