-- MySQL Script generated by MySQL Workbench
-- Tue May  3 13:03:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema renueva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema renueva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `renueva` DEFAULT CHARACTER SET utf8mb4 ;
USE `renueva` ;

-- -----------------------------------------------------
-- Table `renueva`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cat` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`images` (
  `idimg` INT(11) NOT NULL AUTO_INCREMENT,
  `img` LONGBLOB NOT NULL,
  PRIMARY KEY (`idimg`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`articulod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`articulod` (
  `Ar_id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_categoria` INT(11) NOT NULL,
  `idimg` INT(11) NULL DEFAULT NULL,
  `Ar_descripcion` VARCHAR(200) NOT NULL,
  `Ar_precioVenta` DECIMAL(11,2) NOT NULL,
  `Ar_nombre` VARCHAR(50) NOT NULL,
  `Ar_stock` INT(11) NOT NULL,
  `Ar_precioCosto` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`Ar_id`),
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `idimg` (`idimg` ASC) VISIBLE,
  CONSTRAINT `articulod_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `renueva`.`categoria` (`id_categoria`),
  CONSTRAINT `articulod_ibfk_2`
    FOREIGN KEY (`idimg`)
    REFERENCES `renueva`.`images` (`idimg`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`rol` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`usuarios` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `id_rol` INT(11) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(80) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE,
  UNIQUE INDEX `telefono` (`telefono` ASC) VISIBLE,
  INDEX `id_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `renueva`.`rol` (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`servicios` (
  `id_servicio` INT(11) NOT NULL AUTO_INCREMENT,
  `servicio` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_servicio`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`hora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`hora` (
  `idhora` INT(11) NOT NULL AUTO_INCREMENT,
  `hora` TIME NOT NULL,
  PRIMARY KEY (`idhora`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`citas` (
  `id_citas` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` INT(11) NOT NULL,
  `fecha` VARCHAR(10) NOT NULL,
  `idhora` INT(11) NOT NULL,
  `id_servicio` INT(11) NOT NULL,
  `comentario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_citas`),
  INDEX `iduser` (`iduser` ASC) VISIBLE,
  INDEX `id_servicio` (`id_servicio` ASC) VISIBLE,
  INDEX `idhora` (`idhora` ASC) VISIBLE,
  CONSTRAINT `citas_ibfk_1`
    FOREIGN KEY (`iduser`)
    REFERENCES `renueva`.`usuarios` (`iduser`),
  CONSTRAINT `citas_ibfk_2`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `renueva`.`servicios` (`id_servicio`),
  CONSTRAINT `citas_ibfk_3`
    FOREIGN KEY (`idhora`)
    REFERENCES `renueva`.`hora` (`idhora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`estados` (
  `id_estado` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`direccion` (
  `id_direccion` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` INT(11) NOT NULL,
  `calle` VARCHAR(100) NOT NULL,
  `exterior` VARCHAR(5) NOT NULL,
  `interior` VARCHAR(5) NOT NULL,
  `id_estado` INT(11) NOT NULL,
  `colonia` VARCHAR(30) NOT NULL,
  `codigo_postal` INT(5) NOT NULL,
  PRIMARY KEY (`id_direccion`),
  UNIQUE INDEX `iduser` (`iduser` ASC) VISIBLE,
  INDEX `id_estado` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `direccion_ibfk_1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `renueva`.`estados` (`id_estado`),
  CONSTRAINT `direccion_ibfk_2`
    FOREIGN KEY (`iduser`)
    REFERENCES `renueva`.`usuarios` (`iduser`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`inventario` (
  `inv_id` INT(11) NOT NULL AUTO_INCREMENT,
  `inv_date` VARCHAR(14) NOT NULL,
  `inv_total` INT(11) NOT NULL,
  `Ar_id` INT(11) NOT NULL,
  PRIMARY KEY (`inv_id`),
  INDEX `Ar_id` (`Ar_id` ASC) VISIBLE,
  CONSTRAINT `inventario_ibfk_1`
    FOREIGN KEY (`Ar_id`)
    REFERENCES `renueva`.`articulod` (`Ar_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`pedido` (
  `idventa` INT(11) NOT NULL,
  `fecha_hora` VARCHAR(50) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `total` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `usuarios_iduser` INT(11) NOT NULL,
  PRIMARY KEY (`idventa`, `usuarios_iduser`),
  INDEX `fk_pedido_usuarios1_idx` (`usuarios_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_usuarios1`
    FOREIGN KEY (`usuarios_iduser`)
    REFERENCES `renueva`.`usuarios` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `renueva`.`pedido_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renueva`.`pedido_articulo` (
  `pd_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Ar_id` INT(11) NOT NULL,
  `pedido_idventa` INT(11) NOT NULL,
  `pedido_usuarios_iduser` INT(11) NOT NULL,
  PRIMARY KEY (`pd_id`, `pedido_idventa`, `pedido_usuarios_iduser`),
  INDEX `Ar_id` (`Ar_id` ASC) VISIBLE,
  INDEX `fk_pedido_articulo_pedido1_idx` (`pedido_idventa` ASC, `pedido_usuarios_iduser` ASC) VISIBLE,
  CONSTRAINT `pedido_articulo_ibfk_1`
    FOREIGN KEY (`Ar_id`)
    REFERENCES `renueva`.`articulod` (`Ar_id`),
  CONSTRAINT `fk_pedido_articulo_pedido1`
    FOREIGN KEY (`pedido_idventa` , `pedido_usuarios_iduser`)
    REFERENCES `renueva`.`pedido` (`idventa` , `usuarios_iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `renueva`;

DELIMITER $$
USE `renueva`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `renueva`.`citas_before_insert`
BEFORE INSERT ON `renueva`.`citas`
FOR EACH ROW
BEGIN
    DECLARE cuenta_citas INTEGER;
    DECLARE hora INTEGER;
	
    SELECT COUNT(*) FROM citas WHERE  (fecha = NEW.fecha) AND (idhora= NEW.idhora) INTO cuenta_citas;

    IF (New.fecha >= CURDATE()) THEN
		IF (cuenta_citas = 0 )THEN 
			SET NEW.iduser = NEW.iduser;
			SET NEW.fecha = NEW.fecha;
			SET NEW.idhora = NEW.idhora;
			SET NEW.id_servicio = NEW.id_servicio;
            SET NEW.comentario =NEW.comentario;
        END IF;
        IF cuenta_citas>0 THEN
         SIGNAL SQLSTATE '45025' SET MESSAGE_TEXT='Fecha no disponible';
        END IF;
    ELSE 
        SIGNAL SQLSTATE '45005' SET MESSAGE_TEXT='FECHA NO VALIDA';
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
